SELECT ACCESS_USER.ACCOUNTNAME AS "Username",
ACCESS_USER.ACTIVE AS "Activated",
ACCESS_USER.VALID AS "Valid until",
ACCESS_USER.CHANGE_PASSWORD AS "Password must be changed",
ACCESS_USER.PHONE AS "Phone",
ACCESS_USER.FUNCTION AS "Function",
ACCESS_USER.LASTNAME AS "Lastname",
ACCESS_USER.FIRSTNAME AS "Firstname",
ACCESS_USER.EMAIL AS "E-mail",
ACCESS_USER.ORGANISATIONAL_UNIT AS "Organizational unit",
ACCESS_USER.DESCRIPTION AS "Description",
ACCESS_ROLE.NAME AS "Name",
ACCESS_ROLE.DESCRIPTION AS "Description"
FROM ACCESS_USER
JOIN ACCESS_USER_ROLE
ON ACCESS_USER.ID = ACCESS_USER_ROLE.USER_ID
JOIN ACCESS_ROLE
ON ACCESS_USER_ROLE.ROLE_ID = ACCESS_ROLE.ID;
