SELECT TARGET_OBJECT.ABBREVIATION AS "Token", 
TARGET_OBJECT.QUANTITY AS "Count", 
TARGET_OBJECT.NAME AS "Name", 
TARGET_OBJECT_TYPE.LABEL_KEY AS "Type",
TARGET_OBJECT_SUBTYPE.LABEL_KEY AS "Subtype",
SECURITY_ANALYSIS.NECESSITY AS "Necessity",
SECURITY_ANALYSIS.NECESSITY_REASON as "Description"
FROM TARGET_OBJECT
JOIN TARGET_OBJECT_TYPE
ON TARGET_OBJECT.TARGET_OBJECT_TYPE_ID = TARGET_OBJECT_TYPE.ID
JOIN HAS_SUBTYPE
ON TARGET_OBJECT.ID = HAS_SUBTYPE.TARGET_OBJECT_ID
JOIN LINK
ON TARGET_OBJECT.ID = LINK.SLAVE_ID
JOIN EVALUATION
ON LINK.EVALUATION_ID = EVALUATION.ID
JOIN SECURITY_ANALYSIS
on EVALUATION.SECURITY_ANALYSIS_ID = SECURITY_ANALYSIS.ID
JOIN TARGET_OBJECT_SUBTYPE
ON HAS_SUBTYPE.TARGET_OBJECT_SUBTYPE_ID = TARGET_OBJECT_SUBTYPE.ID
WHERE TARGET_OBJECT_TYPE.SAFETY_CONCEPT_VERSION_ID = 47 AND TARGET_OBJECT_SUBTYPE.SAFETY_CONCEPT_VERSION_ID = 47
and TARGET_OBJECT.NAME like 'H%';
