--For one TO:
--SELECT TARGET_OBJECT.ABBREVIATION AS "Token",
--TARGET_OBJECT.QUANTITY AS "Count",
--TARGET_OBJECT.NAME AS "Name",
--TARGET_OBJECT_TYPE.LABEL_KEY AS "Type",
--TARGET_OBJECT_SUBTYPE.LABEL_KEY AS "Subtype",
--SECURITY_ANALYSIS.NECESSITY AS "Necessity",
--SECURITY_ANALYSIS.NECESSITY_REASON as "Description"
--FROM TARGET_OBJECT
--JOIN TARGET_OBJECT_TYPE
--ON TARGET_OBJECT.TARGET_OBJECT_TYPE_ID = TARGET_OBJECT_TYPE.ID
--JOIN HAS_SUBTYPE
--ON TARGET_OBJECT.ID = HAS_SUBTYPE.TARGET_OBJECT_ID
--JOIN LINK
--ON TARGET_OBJECT.ID = LINK.SLAVE_ID
--JOIN EVALUATION
--ON LINK.EVALUATION_ID = EVALUATION.ID
--JOIN SECURITY_ANALYSIS
--on EVALUATION.SECURITY_ANALYSIS_ID = SECURITY_ANALYSIS.ID
--JOIN TARGET_OBJECT_SUBTYPE
--ON HAS_SUBTYPE.TARGET_OBJECT_SUBTYPE_ID = TARGET_OBJECT_SUBTYPE.ID
--WHERE TARGET_OBJECT_TYPE.SAFETY_CONCEPT_VERSION_ID = 47 AND TARGET_OBJECT_SUBTYPE.SAFETY_CONCEPT_VERSION_ID = 47
--and TARGET_OBJECT.NAME like 'H%';

-- For multiple TOs
--SELECT TARGET_OBJECT.ABBREVIATION AS "Token",
--TARGET_OBJECT.QUANTITY AS "Count",
--TARGET_OBJECT.NAME AS "Name",
--TARGET_OBJECT_TYPE.LABEL_KEY AS "Type",
--TARGET_OBJECT_SUBTYPE.LABEL_KEY AS "Subtype",
--SECURITY_ANALYSIS.NECESSITY AS "Necessity",
--SECURITY_ANALYSIS.NECESSITY_REASON as "Description"
--FROM TARGET_OBJECT
--JOIN TARGET_OBJECT_TYPE
--ON TARGET_OBJECT.TARGET_OBJECT_TYPE_ID = TARGET_OBJECT_TYPE.ID
--JOIN HAS_SUBTYPE
--ON TARGET_OBJECT.ID = HAS_SUBTYPE.TARGET_OBJECT_ID
--JOIN LINK
--ON TARGET_OBJECT.ID = LINK.SLAVE_ID
--JOIN EVALUATION
--ON LINK.EVALUATION_ID = EVALUATION.ID
--JOIN SECURITY_ANALYSIS
--on EVALUATION.SECURITY_ANALYSIS_ID = SECURITY_ANALYSIS.ID
--JOIN TARGET_OBJECT_SUBTYPE
--ON HAS_SUBTYPE.TARGET_OBJECT_SUBTYPE_ID = TARGET_OBJECT_SUBTYPE.ID
--WHERE TARGET_OBJECT_TYPE.SAFETY_CONCEPT_VERSION_ID = 47 AND TARGET_OBJECT_SUBTYPE.SAFETY_CONCEPT_VERSION_ID = 47
--and TARGET_OBJECT.NAME IN (
--SELECT TOS."NAME" as Linked_to_IC
--from TARGET_OBJECT TOS
--left join "LINK" L
--on L.SLAVE_ID=TOS."ID"
--and L.SAFETY_CONCEPT_VERSION_ID=TOS.SAFETY_CONCEPT_VERSION_ID
--left join TARGET_OBJECT TOM
--on TOM."ID"=L.MASTER_ID
--and TOM.SAFETY_CONCEPT_VERSION_ID=L.SAFETY_CONCEPT_VERSION_ID
--
--where L.SAFETY_CONCEPT_VERSION_ID=47
--AND L.SLAVE_ID<>L.MASTER_ID
--and L.DELETED=0
--);   // TODO Add suggestion to query

SELECT TARGET_OBJECT.ABBREVIATION AS "Token",
TARGET_OBJECT.QUANTITY AS "Count",
TARGET_OBJECT.NAME AS "Name",
TARGET_OBJECT_TYPE.LABEL_KEY AS "Type",
TARGET_OBJECT_SUBTYPE.LABEL_KEY AS "Subtype",
SECURITY_ANALYSIS.NECESSITY AS "Necessity",

SECURITY_ANALYSIS.SPECIAL_SCENARIO,
SECURITY_ANALYSIS.NO_MODELING,
(SELECT MAX (CATEGORY)  FROM PROTECTION_REQUIREMENT
WHERE PROTECTION_REQUIREMENT.TYPE = 'RATING'
AND  PROTECTION_REQUIREMENT.TARGET_OBJECT_ID = TARGET_OBJECT.ID AND
PROTECTION_REQUIREMENT.SAFETY_CONCEPT_VERSION_ID = TARGET_OBJECT.SAFETY_CONCEPT_VERSION_ID) as PR,

SECURITY_ANALYSIS.NECESSITY_REASON as "Description"
FROM TARGET_OBJECT
JOIN TARGET_OBJECT_TYPE
ON TARGET_OBJECT.TARGET_OBJECT_TYPE_ID = TARGET_OBJECT_TYPE.ID
JOIN HAS_SUBTYPE
ON TARGET_OBJECT.ID = HAS_SUBTYPE.TARGET_OBJECT_ID
JOIN LINK
ON TARGET_OBJECT.ID = LINK.SLAVE_ID
JOIN EVALUATION
ON LINK.EVALUATION_ID = EVALUATION.ID
JOIN SECURITY_ANALYSIS
on EVALUATION.SECURITY_ANALYSIS_ID = SECURITY_ANALYSIS.ID
JOIN TARGET_OBJECT_SUBTYPE
ON HAS_SUBTYPE.TARGET_OBJECT_SUBTYPE_ID = TARGET_OBJECT_SUBTYPE.ID

JOIN PROTECTION_REQUIREMENT
on TARGET_OBJECT.ID = PROTECTION_REQUIREMENT.TARGET_OBJECT_ID

WHERE TARGET_OBJECT_TYPE.SAFETY_CONCEPT_VERSION_ID = 47 AND TARGET_OBJECT_SUBTYPE.SAFETY_CONCEPT_VERSION_ID = 47
AND TARGET_OBJECT.NAME IN (
-- Subquery
SELECT TOS."NAME" as Linked_to_IC
from TARGET_OBJECT TOS
left join "LINK" L
on L.SLAVE_ID=TOS."ID"
and L.SAFETY_CONCEPT_VERSION_ID=TOS.SAFETY_CONCEPT_VERSION_ID
left join TARGET_OBJECT TOM
on TOM."ID"=L.MASTER_ID
and TOM.SAFETY_CONCEPT_VERSION_ID=L.SAFETY_CONCEPT_VERSION_ID
where L.SAFETY_CONCEPT_VERSION_ID=47
AND L.SLAVE_ID<>L.MASTER_ID
and L.DELETED=0);



SELECT TARGET_OBJECT.ABBREVIATION AS "Token",
TARGET_OBJECT.QUANTITY AS "Count",
TARGET_OBJECT.NAME AS "Name",
TARGET_OBJECT_TYPE.LABEL_KEY AS "Type",
TARGET_OBJECT_SUBTYPE.LABEL_KEY AS "Subtype",
SECURITY_ANALYSIS.NECESSITY AS "Necessity",

SECURITY_ANALYSIS.SPECIAL_SCENARIO,
SECURITY_ANALYSIS.NO_MODELING,
(SELECT MAX (CATEGORY)  FROM PROTECTION_REQUIREMENT
WHERE PROTECTION_REQUIREMENT.TYPE = 'RATING'
AND  PROTECTION_REQUIREMENT.TARGET_OBJECT_ID = TARGET_OBJECT.ID AND
PROTECTION_REQUIREMENT.SAFETY_CONCEPT_VERSION_ID = TARGET_OBJECT.SAFETY_CONCEPT_VERSION_ID) as PR,

SECURITY_ANALYSIS.NECESSITY_REASON as "Description"
FROM TARGET_OBJECT
JOIN TARGET_OBJECT_TYPE
ON TARGET_OBJECT.TARGET_OBJECT_TYPE_ID = TARGET_OBJECT_TYPE.ID
JOIN HAS_SUBTYPE
ON TARGET_OBJECT.ID = HAS_SUBTYPE.TARGET_OBJECT_ID
JOIN LINK
ON TARGET_OBJECT.ID = LINK.SLAVE_ID
JOIN EVALUATION
ON LINK.EVALUATION_ID = EVALUATION.ID
JOIN SECURITY_ANALYSIS
on EVALUATION.SECURITY_ANALYSIS_ID = SECURITY_ANALYSIS.ID
JOIN TARGET_OBJECT_SUBTYPE
ON HAS_SUBTYPE.TARGET_OBJECT_SUBTYPE_ID = TARGET_OBJECT_SUBTYPE.ID

JOIN PROTECTION_REQUIREMENT
on TARGET_OBJECT.ID = PROTECTION_REQUIREMENT.TARGET_OBJECT_ID

WHERE TARGET_OBJECT_TYPE.SAFETY_CONCEPT_VERSION_ID = 47 AND TARGET_OBJECT_SUBTYPE.SAFETY_CONCEPT_VERSION_ID = 47
AND TARGET_OBJECT.NAME IN (
-- Subquery
SELECT TOS."NAME" as Linked_to_IC
from TARGET_OBJECT TOS
left join "LINK" L
on L.SLAVE_ID=TOS."ID"
and L.SAFETY_CONCEPT_VERSION_ID=TOS.SAFETY_CONCEPT_VERSION_ID
left join TARGET_OBJECT TOM
on TOM."ID"=L.MASTER_ID
and TOM.SAFETY_CONCEPT_VERSION_ID=L.SAFETY_CONCEPT_VERSION_ID
where L.SAFETY_CONCEPT_VERSION_ID=47
AND L.SLAVE_ID<>L.MASTER_ID
and L.DELETED=0);
