--select  TOM."NAME" as IC,
--TOS."NAME" as Linked_to_IC
--from TARGET_OBJECT TOS
--left join "LINK" L
--on L.SLAVE_ID=TOS."ID"
--and L.SAFETY_CONCEPT_VERSION_ID=TOS.SAFETY_CONCEPT_VERSION_ID
--left join TARGET_OBJECT TOM
--on TOM."ID"=L.MASTER_ID
--and TOM.SAFETY_CONCEPT_VERSION_ID=L.SAFETY_CONCEPT_VERSION_ID
--
--where L.SAFETY_CONCEPT_VERSION_ID=47
--and L.SLAVE_ID<>L.MASTER_ID
--and L.DELETED=0

(SELECT MAX (category)  FROM PROTECTION_REQUIREMENT pr
WHERE pr.TYPE = 'RATING'
AND  pr.TARGET_OBJECT_ID = targetObject.ID
AND pr.SAFETY_CONCEPT_VERSION_ID = targetObject.SAFETY_CONCEPT_VERSION_ID)

